### ISSUE TITLE
Script for placeholder replacing

### ISSUE THREAD

**Issue by mamuz** [mjacobus/php-library-skeleton#1]
After cloning i need a script, which replaces all placeholder in all plain text files, such as {library_name} and {year}.

@mjacobus what do you think?

**Comment by mjacobus** [comment]
I think this is what you are looking for: [./bin/configure_project.sh](https://github.com/mjacobus/php-library-skeleton/blob/master/bin/configure_project.sh)

Is it @mamuz?

**Comment by mamuz** [comment]
exactly
